### ISSUE TITLE
Random crashes?

### ISSUE THREAD

**Issue by mjjones0** [Rei-x/discord-speech-recognition#34]
node:events:505
      throw er; // Unhandled 'error' event
      ^

TypeError: The compressed data passed is corrupted
    at Decoder._decode (C:\Users\serap\Desktop\discordspeechbot\discord-speech-recognition\examples\simpleBot\node_modules\prism-media\src\opus\Opus.js:64:25) 
    at Decoder._transform (C:\Users\serap\Desktop\discordspeechbot\discord-speech-recognition\examples\simpleBot\node_modules\prism-media\src\opus\Opus.js:204:22)
    at Decoder.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Decoder.Writable.write (node:internal/streams/writable:334:10)
    at AudioReceiveStream.ondata (node:internal/streams/readable:754:22)
    at AudioReceiveStream.emit (node:events:527:28)
    at AudioReceiveStream.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
Emitted 'error' event on Decoder instance at:
    at Decoder.onerror (node:internal/streams/readable:773:14)
    at Decoder.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    
    This is periodically happening when I use SimpleBot. I don't really see how it's something I wrote, though I did modify it a bit. 
    
    I have it joining a channel, and it doesn't leave it just continues functioning when you trigger it.

**Comment by Rei-x** [comment]
try to update `@discordjs/voice` and `@discordjs/opus` packages and tell me if that fixed the issue for you

**Comment by mjjones0** [comment]
I did and it did not

**Comment by Rei-x** [comment]
are you using web version of discord?

**Comment by Rei-x** [comment]
Try to use the newest version for discord.js v14, it shouldn't happen now
